### ISSUE TITLE
Quick call

### ISSUE THREAD

**Issue by mahmoud422** [KuChainNetwork/Project-Decalogue#1]
Quick call It is just an idea, but it will benefit I suggest you design an icon that enters the tool so that the executable file is in bundles 
intended When installing the project in the system and entering the project and opening the file, it automatically moves to packages in the system and the next time we open the project we do not enter the project files, but we will write only the file name and it will automatically enter into the project ...

**Comment by mahmoud422** [comment]
My email 
Xsatan80@gmail.com

**Comment by Pisces-Anjou** [comment]
Hi,



Thanks for your proposal.

Please read the rules carefully before submitting your proposal. Proposal which doesn't follow the report model will be considered invalid.

Thanks for your attention. Please keep trying and help us improve our chain.



Regards

KuChain team
