### ISSUE TITLE
[DOC] Features for easier trading

### ISSUE THREAD

**Issue by ridhataq** [KuChainNetwork/Project-Decalogue#6]
**Type of Proposal**

- [&check;] Feature Request (e.g. functionality) 

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance) 

- [ ] Application Development

- [ ] Others

  

**Background**

Ease of use for traders, especially those who are new to KuCoin, based on my personal experience
when I first using Kucoin.

**Describe The Proposal (No more than 50 words)** 

Simplifying futures funds transfer and auto deposit margin.

**Business Model (Optional for underlying technology)** 

Making transferring funds and futures trading easier for traders so they will feel more comfortable in using KuCoin and hopefully will stay and be a loyal customer.

**Implementation Steps (Optional for economic model)** 

1.  Funds transfer
As of now, traders have to transfer their funds from main account to trading account first then transfer it again to futures account in order to trade (that was what I experienced and got confused at first because I thought my funds went missing).
It would be more convenient for traders if they can directly transfer their funds from main account to trading, futures, or margin account, so they only have to do it one time instead of two times.

2. Auto deposit margin
In futures trading, traders can enable "auto deposit margin" feature after their order got filled (again, this was based on personal experience). It would be a hassle if a trader isn't online at the time their order got filled, resulting they can't enable the "auto deposit margin" feature.
Having that feature available during order placing will be a neat solution, so traders won't have to wait until their order got filled to activate it.

**Expected Outcome**
Traders will have a smoother, hassle free trade while trading on KuCoin.

**Timetable (Optional)** 

As soon as possible, preferably once KuChain goes live.

**Additional Context (Optional)** 
N/A

**Contact Information**
ridhataqobalallahlah@gmail.com

**Comment by Pisces-Anjou** [comment]
Hi，

Thanks for your submission.
Please note that Project-Decalogue (Proposal Award Program) is related to KuChain, which has nothing to do with KuCoin. Your proposal is out of scope. We will forward it to KuCoin related department. They will contact you if they need.
Thanks for your attention. Please keep trying and help us improve our chain.

Regards
KuChain team
