### ISSUE TITLE
[DOC] Issue with Older Version Kucoin (Maker and Taker fee)

### ISSUE THREAD

**Issue by playforpride** [KuChainNetwork/Project-Decalogue#7]
Type of Proposal

- [ ] Feature Request (e.g. functionality) 

- [ ] Economic Model

- [ ] Underlying Technology (e.g. performance) 

- [ ] Application Development

- [✓] Others

  

Background

Trading fee (Maker and Taker fee) showing wrong data (minor bug)

Describe The Proposal (No more than 50 words)

Need to fix the trading fee issue in the older version of Kucoin

Implementation Steps (Replicate the issue)

1. After a successful login, it looks perfect as per the below picture (Maker and Taker fee)

![Screenshot_2](https://user-images.githubusercontent.com/59907727/88192584-e6416f80-cc66-11ea-88f5-b1bab0afaa89.jpg)

2. But after clicking on the Old Version (top right corner), it's showed wrong trading fee as below (Maker and Taker fee)

![Screenshot_1](https://user-images.githubusercontent.com/59907727/88193122-7e3f5900-cc67-11ea-9569-479632e39b80.jpg)

3. Now, if we click on the right arrow key as shown in the below picture (pic 3) then it will fix automatically(pic 4).

![Screenshot_3](https://user-images.githubusercontent.com/59907727/88193251-a3cc6280-cc67-11ea-9cfa-ae688497dd37.jpg)

![Screenshot_4](https://user-images.githubusercontent.com/59907727/88193341-c2325e00-cc67-11ea-8083-29b8389ecf9e.jpg)

4. After that, if we click on Kucoin home page then also it's working fine as below (Maker and Taker fee)

![Screenshot_5](https://user-images.githubusercontent.com/59907727/88193554-01f94580-cc68-11ea-9a4b-b93785f8f663.jpg)

5. Now, if we refresh the page using [F5] button or reload the page using browser reload then the same issue occurs.

![Screenshot_6](https://user-images.githubusercontent.com/59907727/88193826-500e4900-cc68-11ea-80f2-4167f774ec9a.jpg)

Expected Outcome
It will help our old version of Kucoin users to get correct information related to the Trading fee (Maker and Taker fee). Also, fix the minor bug.

Contact Information
suman.gope680@gmail.com

**Comment by Pisces-Anjou** [comment]
Hi，

Thanks for your submission.
Please note that Project-Decalogue (Proposal Award Program) is related to KuChain, which has nothing to do with KuCoin. Your proposal is out of scope. We will forward it to KuCoin related department. They will contact you if they need.
Thanks for your attention. Please keep trying and help us improve our chain.

Regards
KuChain Team
